name: "snapshot"
version: "0.1.0"
usage: "Create a visual snapshot of your packaged Helm chart as a Meshery Snapshot"
description: "A Helm plugin to generate Meshery Snapshots from Helm charts using Go"
command: "$HELM_PLUGIN_DIR/helm-plugin-snapshot"
hooks:
  install: |
    echo 'Installing Meshery Snapshot Plugin...'
    # No need to manually install here since Helm manages this.
    echo 'Meshery Snapshot Plugin installed successfully.'
  uninstall: |
    echo 'Uninstalling Meshery Snapshot Plugin...'
    # Uninstallation hook, if necessary
    echo 'Meshery Snapshot Plugin uninstalled successfully.'
