name: Build and Deploy Site
on:
  push:
    branches: [ master ]
    paths:
      - '!**'
      - 'site/**'
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.1

      - name: Install and Build 🔧 
        run: |
          make setup-libs
          make build

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.0.0
        with:
          branch: site # The branch the action should deploy to.
          folder: site/build # The folder the action should deploy.
          clean: true