name: Notify Email
on: 
  workflow_dispatch:
    inputs:
      to:
        description: 'recipient'
        required: false
  workflow_call:
    inputs:
      to:
        description: 'recipient'
        type: string
        required: false
jobs:
  email:
    name: Prepare email
    runs-on: "ubuntu-latest"
    steps:
      - name: Send email
        uses: dawidd6/action-send-mail@v3.7.1
        with:
          # Required mail server address:
          server_address: smtp.gmail.com
          # Required mail server port:
          server_port: 465
          # Optional (recommended): mail server username:
          username: ${{secrets.MAIL_USERNAME}}
          # Optional (recommended) mail server password:
          password: ${{secrets.MAIL_PASSWORD}}
          # Required mail subject:
          subject: New Meshery Release
          # Required recipients' addresses:
          to: lee.calcote@layer5.io
          # Required sender full name (address can be skipped):
          from: Meshery # <user@example.com>
          # Optional whether this connection use TLS (default is true if server_port is 465)
          secure: true
          # Optional plain body:
          body: Meshery Released!
          # Optional HTML body read from file:
          html_body: file://meshery-release-notifier.html
          # Optional carbon copy recipients:
          cc: leecalcote@icloud.com
          # Optional blind carbon copy  recipients:
          # bcc: r2d2@example.com,hansolo@example.com
          # Optional recipient of the email response:
          reply_to: no-reply@meshery.io
          # Optional unsigned/invalid certificates allowance:
          ignore_cert: true
          # Optional converting Markdown to HTML (set content_type to text/html too):
          convert_markdown: true
          # Optional attachments:
          attachments: attachments.zip,git.diff,./dist/static/*.js
          # Optional priority: 'high', 'normal' (default) or 'low'
          priority: low

