name: Publish Assets
on: 
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to be released'
        required: true
        default: 'stale'

jobs:
  release:
    name: publish assets
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 10
      matrix:
        os: ["ubuntu-18.04","macos-latest"]
        include:
          - os: "ubuntu-18.04"
            distro: "linux"
          - os: "macos-latest"
            distro: "darwin"
    steps:
    - name: pull packages
      run: |
        url=$(curl -H "Authorization: token ${{ secrets.GH_ACCESS_TOKEN}}" "https://api.github.com/repos/layer5labs/meshery-extensions/releases" | jq -r '.[] | select(.tag_name == "${{ github.event.inputs.version }}")' | jq -r .assets | jq -r '.[] | select(.name == "provider-${{ matrix.distro }}.tar.gz")' | jq -r .browser_download_url)
        echo $url
        curl -o /home/runner/work/provider-${{ matrix.distro }}.tar.gz $url
    - name: publish
      uses: ncipollo/release-action@v1
      with:
        token: ${{ secrets.GH_ACCESS_TOKEN }}
        tag:  ${{ github.event.inputs.version }}
        name: Meshery Extensions for Meshery version ${{ github.event.inputs.version }}
        allowUpdates: true
        artifactErrorsFailBuild: true
        artifacts: /home/runner/work/provider-${{ matrix.distro }}.tar.gz
        omitNameDuringUpdate: true
        replacesArtifacts: true
