# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages
name: Publish Meshery Design Embed React Package

on:
  workflow_dispatch:
    inputs:
      release-version:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_ACCESS_TOKEN }}
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: |
          ls &&
          cd meshery-design-embed  && 
          npm install && 
          npm run build

  tag-version:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_ACCESS_TOKEN }}
      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Generate new version
        run: cd meshery-design-embed && npm version ${{ github.event.inputs.release-version }}

  publish-gpr:
    needs: tag-version
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_ACCESS_TOKEN }}
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: "https://registry.npmjs.org"
          scope: "@layer5"

      - name: Run npm release
        run: cd meshery-design-embed && npm publish --verbose
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Commit and push version change
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_user_name: l5io
          commit_user_email: l5io@layer5.io
          commit_author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          commit_options: "--signoff"
          commit_message: "[Release Meshery Embed ]: release version  ${{ github.event.inputs.release-version }}"
          repo: meshery-extensions-packages
