name: Release Chart
on:
  workflow_call:
  workflow_dispatch:
    inputs:
      logLevel:
        description: "Log level"
        required: true
        default: "warning"
      release-ver:
        description: "Release Version"
        required: false
        default: "latest"
jobs:
  validate:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          path: cloud
          repository: layer5io/meshery-cloud
          ref: master
          token: ${{ secrets.GH_ACCESS_TOKEN }}
      - uses: azure/setup-helm@v4
        id: install
      - name: validate cloud chart
        run: helm lint cloud/install/kubernetes --with-subcharts
  release-chart:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          path: ${{ github.workspace }}/cloud
          repository: layer5io/meshery-cloud
          ref: master
          token: ${{ secrets.GH_ACCESS_TOKEN }}          
      - name: Debug commands
        run: |
          ls;
          pwd;
          cd cloud;
      - name: Publish Helm chart for release version 
        if:  github.event_name == 'workflow_call'
        uses: stefanprodan/helm-gh-pages@master
        with:
          token: ${{ secrets.GH_ACCESS_TOKEN }}
          charts_dir: install/kubernetes
          owner: layer5io
          repository: docs
          branch: master
          target_dir: charts
          commit_username: l5io
          commit_email: l5io@layer5.io
          chart_version: ${{ steps.vars.outputs.tag }}
          app_version: ${{ steps.vars.outputs.tag }}

      - name: Manually publish Helm chart with release version
        if: github.event_name == 'workflow_dispatch'
        uses: stefanprodan/helm-gh-pages@master
        with:
          token: ${{ secrets.GH_ACCESS_TOKEN }}
          charts_dir: install/kubernetes
          owner: layer5io
          repository: docs
          branch: master
          charts_url: https://docs.layer5.io/charts
          target_dir: charts
          commit_username: l5io
          commit_email: l5io@layer5.io
          chart_version: ${{github.event.inputs.release-ver}}
          app_version: ${{github.event.inputs.release-ver}}
